# Generated by Django 4.0.3 on 2023-08-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('breed', models.CharField(max_length=255, verbose_name='breed')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='weight')),
                ('hair', models.CharField(max_length=255, verbose_name='hair')),
                ('food_preference', models.CharField(max_length=255, verbose_name='food_preference')),
                ('photo', models.ImageField(upload_to='', verbose_name='photo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.user', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pet',
                'db_table': 'pet',
            },
        ),
    ]
