# Generated by Django 4.0.3 on 2023-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_rename_product_goods_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
                'db_table': 'category',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='categories',
            field=models.ManyToManyField(to='pets.category', verbose_name='categories'),
        ),
    ]
