# Generated by Django 4.0.3 on 2023-08-21 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_category_goods_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='count')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.goods', verbose_name='goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'cart',
                'db_table': 'cart',
            },
        ),
    ]
