# Generated by Django 4.0.3 on 2023-08-22 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('goods_info_json_str', models.TextField(verbose_name='goods info')),
                ('delivery_info_json_str', models.TextField(verbose_name='delivery info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'order',
                'db_table': 'order',
            },
        ),
    ]
