# Generated by Django 4.0.3 on 2023-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('addr', models.TextField(verbose_name='addr')),
                ('notes', models.TextField(verbose_name='notes')),
            ],
            options={
                'verbose_name': 'delivery',
                'verbose_name_plural': 'delivery',
                'db_table': 'delivery',
            },
        ),
    ]
