# Generated by Django 4.0.3 on 2023-08-24 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_delivery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.goods', verbose_name='goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.order', verbose_name='order')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pets.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'order comment',
                'verbose_name_plural': 'order comment',
                'db_table': 'order_comment',
            },
        ),
    ]
