# Generated by Django 4.0.3 on 2023-08-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_ordercomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='GoodsCategory',
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': 'goods category', 'verbose_name_plural': 'goods category'},
        ),
        migrations.AlterModelTable(
            name='goodscategory',
            table='goods_category',
        ),
    ]
