# Generated by Django 4.0.3 on 2023-08-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_rename_category_goodscategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='categories',
        ),
    ]
