# Generated by Django 4.0.3 on 2023-08-29 03:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_info_json_str', models.TextField(verbose_name='service_info_json_str')),
                ('pet_info_json_str', models.TextField(verbose_name='service_info_json_str')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pets.seller', verbose_name='seller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'bookings',
                'verbose_name_plural': 'bookings',
                'db_table': 'bookings',
            },
        ),
    ]
