# Generated by Django 4.0.3 on 2023-08-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0021_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='appointment_time',
            field=models.DateTimeField(default=None, verbose_name='appointment_time'),
        ),
    ]
