# Generated by Django 4.0.3 on 2023-08-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_bookings_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total_price'),
        ),
    ]
