# Generated by Django 4.0.3 on 2023-08-30 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0024_forum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pets.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'community',
                'db_table': 'community',
            },
        ),
    ]
