# Generated by Django 4.0.3 on 2023-08-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0025_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='title'),
        ),
    ]
