# Generated by Django 4.0.3 on 2023-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0028_community_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'unshipped'), (2, 'in transit'), (3, 'arrival')], default=1, verbose_name='status'),
        ),
    ]
