# Generated by Django 4.0.3 on 2023-08-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0029_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(choices=[(1, 'Successfully Booked'), (2, 'In progress'), (3, 'Order completion')], default=1, verbose_name='status'),
        ),
    ]
